name: 'get-istioctl'
description: 'Get a specific version of istioctl using semver match'
runs:
  using: 'node16'
  main: 'index.js'
inputs:
  version:
    description: "a semver matching expression, indicating which istio version
    is of interest.  the max satisfying version will be returned."
    required: true
  os:
    required: false
    default: local
    description: "the target operating system, must be one of linux, win, osx, local (default)"
  arch:
    required: false
    default: local
    description: "the required architecture for binaries.  currently supports amd64, arm64, armv7, and local (default)"
outputs:
  version:
    description: "the selected istioctl version"
  major:
    description: "the major portion of the selected istioctl version"
  minor:
    description: "the minor portion of the selected istioctl version"
  patch:
    description: "the patch portion of the selected istioctl version"
  istioctl-url:
    description: the url for downloading the specified istioctl
  istio-url:
    description: the url for downloading the specified istio binaries

