apiVersion: v1
kind: Pod
metadata:
  name: loadtest
  namespace: test
  labels:
    app: loadtest
spec:
  containers:
  - name: loadtest
    image: stefanprodan/loadtest
    command: ['sh', '-c', 'while true; do sleep 30; done;']
