apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: istio
  chart:
    repository: https://storage.googleapis.com/istio-release/releases/1.1.4/charts
    name: istio
    version: 1.1.4
  values:
    # pilot configuration
    pilot:
      enabled: true
      autoscaleEnabled: true
      sidecar: true
      resources:
        requests:
          cpu: 10m
          memory: 128Mi

    # ingress configuration
    gateways:
      enabled: true
      istio-ingressgateway:
        type: LoadBalancer
        autoscaleEnabled: false
        autoscaleMax: 1

    # sidecar-injector webhook configuration
    sidecarInjectorWebhook:
      enabled: true

    # security configuration
    security:
      enabled: true

    # galley configuration
    galley:
      enabled: true

    # mixer configuration
    mixer:
      policy:
        enabled: false
        replicaCount: 1
        autoscaleEnabled: false
      telemetry:
        enabled: true
        replicaCount: 1
        autoscaleEnabled: false
      resources:
        requests:
          cpu: 10m
          memory: 128Mi

    # addon prometheus configuration
    prometheus:
      enabled: true
      scrapeInterval: 5s

    # addon jaeger tracing configuration
    tracing:
      enabled: true

    # common settings
    global:
      # sidecar settings
      proxy:
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 2000m
            memory: 256Mi
      controlPlaneSecurityEnabled: false
      mtls:
        enabled: false
      useMCP: false