name: test-get

on:
  workflow_dispatch:

jobs:
  test-my-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: doit
      id: doit
      uses: ./.github/actions/get-istioctl
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Get the output time
      run: |
        echo "Selected version ${{ steps.doit.outputs.version }}"
        echo "All outputs ${{ steps.doit.outputs }}"
